version: '3.9'
services:
  liquibase-dryrun:
    platform: linux/arm64
    build:
      dockerfile: LiquibaseDockerfile
      context: .
    command: --url=jdbc:mysql://db:3306/db --username=user --password=pass --changeLogFile=changelog.xml updateSql
    volumes:
      - ./changelog.xml:/liquibase/changelog.xml
      - ./changelogs:/liquibase/db-changelogs
    restart: always
    depends_on:
      - db

  liquibase-update:
    platform: linux/arm64
    build:
      dockerfile: LiquibaseDockerfile
      context: .
    command: --url=jdbc:mysql://db:3306/db --username=user --password=pass --changeLogFile=changelog.xml update
    volumes:
      - ./changelog.xml:/liquibase/changelog.xml
      - ./changelogs:/liquibase/db-changelogs
    restart: always
    depends_on:
      - db

  liquibase-rollback:
    platform: linux/arm64
    build:
      dockerfile: LiquibaseDockerfile
      context: .
    command: --url=jdbc:mysql://db:3306/db --username=user --password=pass --changeLogFile=changelog.xml rollbackCount 1
    volumes:
      - ./changelog.xml:/liquibase/changelog.xml
      - ./changelogs:/liquibase/db-changelogs
    restart: always
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: 'pass'
       MYSQL_DATABASE: 'db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'pass'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
